### PR TITLE
Commented out the styling section

### PR DESCRIPTION
**Pull request by ArdJonker**

### CODE REVIEW

**Review by Flix6x — APPROVED** [review]
If you comment it out, doesn't that just mean it *also* becomes useless outside of GitHub?

**Comment by ArdJonker** [comment]
No, the <!-- comment is HTML commenting, this is a known way of wrapping css in HTML.

**Comment by nhoening** [comment]
But this is not an HTML file. It's Markdown.

It will not be recognized by Markdown parsers.

Why not delete it?

**Comment by ArdJonker** [comment]
My designer hart would break ;-)..
It maximises line length, which is "needed" for readability.

**Comment by nhoening** [comment]
But where? Where is the content of this Readme rendered as HTML?

**Comment by ArdJonker** [comment]
In PyCharm it renders full width of the screen..

**Pull request merged**
