### PR TITLE
Refactor calendar handling for efficiency

### PR DESCRIPTION
**Pull request by ArdJonker**
Unfortunately several (un-related) issues where committed to this branche so it is a little bit inter-twined.
The commits are marked with the issues numbers.

### CODE REVIEW

**Comment by Flix6x** [comment]
So there are only 3 (?) commits that need a review, and the rest belongs in different PRs, right? I'd rather make a new clean PR with those 3 relevant commits cherry picked. I can do that (later) if you need me to. What do you want to do with the other commits?

**Comment by ArdJonker** [comment]
Yes, all commits related to issue #67.
I researched splitting this into other branches (which i expect to be needed for sepearte PRs) but that overwhelmed me a bit..

**Comment by Flix6x** [comment]
Moved to https://github.com/SeitaBV/v2g-liberty/pull/75.

**Review by Flix6x — APPROVED** [review]
The original PR mixed several issues, most of which we factored out to different PRs. I'm approving the remaining two issues that this PR now addresses, with some suggestions for small improvements.

Closes #71.
Closes #67.

**Pull request merged**
