### PR TITLE
#125 add user-set min and max to trigger message

### PR DESCRIPTION
**Pull request by ArdJonker**

### CODE REVIEW

**Review by Flix6x — COMMENTED** [review]
I'd make sure that no minima can be set to a higher value than the max.

**Comment by ArdJonker** [comment]
The min/max constrains are built into the globals at reading the user settings and translating them to CONSTANTS.

**Comment by Flix6x** [comment]
Do the user settings mapped to the soc-max and soc-minima fields guarantee that the soc-minima are equal or lower than the soc-max? Are they derived from a single user setting or can they be set separately?

**Comment by ArdJonker** [comment]
They are set separately, the user is informed in secrets to:
 keep SoC min between 10 and 30%
 keep SoC max between 60 and 100%
 And globals.py guards these limits

**Comment by ArdJonker** [comment]
Alterations due to out-of-limits values in secrets.yaml are logged.

**Comment by ArdJonker** [comment]
The FlexMeasures client calculates CAR_MIN_SOC_IN_KWH and CAR_MAX_SOC_IN_KWH based in these percentages and the CAR_MAX_CAPACITY_IN_KWH

**Review by Flix6x — APPROVED** [review]

**Pull request merged**
